name: ci

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Test with the Go CLI
        run: go test ./...

  release:
    if: github.ref == 'refs/heads/main' && (contains(github.event.head_commit.message, 'release-please--branches') || startsWith(github.event.head_commit.message, 'bump'))
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PEM }}

      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Get and azcopy
        run: |
            wget https://aka.ms/downloadazcopy-v10-windows -O azcopy.zip
            unzip azcopy.zip
            cd azcopy_windows_amd64*
            mv azcopy.exe ../azcopy.exe
      - name: Get Azure cli
        run: wget https://aka.ms/installazurecliwindowsx64 -O azcli.msi

      - name: Build golang
        run: |
          GOOS=windows GOARCH=amd64 go build  
          ls -la

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json

      - name: Add Binary release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          name: "${{ steps.release.outputs.tag_name }}"
          files: |
            .release-please-manifest.json 
            azcopy.exe 
            azcli.msi 
            flight-search.exe
          
