name: ci

permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Test with the Go CLI
        run: go test ./...

  release:
    if: github.ref == 'refs/heads/main' && (contains(github.event.head_commit.message, 'release-please--branches') || startsWith(github.event.head_commit.message, 'bump'))
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PEM }}

      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Build golang
        run: |
          GOOS=windows GOARCH=amd64 go build  
          ls -la

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
          
      - name: extract Version 
        run: | 
            VERSION=${{ github.event.release.tag_name }}
            echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
      
      - name: Create a release zip file
        if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'release-please--branches')
        run: zip "${{ steps.release.outputs.tag_name }}.zip" flight-search.exe .release-please-manifest.json

      - name: Add Binary release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'release-please--branches')
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          tag_name: "${{ steps.release.outputs.tag_name }}"
          files: "${{ steps.release.outputs.tag_name }}.zip"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Release to packages
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
