name: ci

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .

      - name: Test with the Go CLI
        run: go test ./...

  release:
    if: github.ref == 'refs/heads/main' && (contains(github.event.head_commit.message, 'release-please--branches') || startsWith(github.event.head_commit.message, 'bump'))
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PEM }}

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json

      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: "${{ steps.generate_token.outputs.token }}"
          goos: windows
          goarch: amd64
          release_name: "${{ steps.release.outputs.tag_name }}"
          pre_command: "wget https://aka.ms/downloadazcopy-v10-windows -O azcopy.zip && wget https://aka.ms/installazurecliwindowsx64 -O azcli.msi && ls -la"
          extra_files: azcopy.zip azcli.exe
