name: release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "main"

jobs:
  release:
    if: contains(github.event.head_commit.message, 'release-please--branches') || startsWith(github.event.head_commit.message, 'bump')
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: "${{ secrets.FLIGHT_SEARCH_TOKEN  }}"
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
