name: ci

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  release:
    if: |
    (contains(github.event.head_commit.message, 'release') && startsWith(github.event.head_commit.message, chore(main))) &&  || startsWith(github.event.head_commit.message, 'bump')
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN  }}"
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
